<?php


namespace common\base;

use yii\db\ActiveRecord;

class SyActiveRecord extends ActiveRecord
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取单条信息
     * @param $array
     */
    public static function throwErrorMsg($model)
    {
        $errors = $model->getFirstErrors();
        $msg = is_array($errors) ? $errors : ['no message'];
        throw new ErrorException(array_pop($msg));
    }
}